# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
